### PR TITLE
security scan: update external libraries

### PR DESCRIPTION
**Pull request by maximthomas**
please, squash and merge

### CODE REVIEW

**Comment by maximthomas** [comment]
to build in travis-ci, need to build [OpenIdentityPlatform/commons](https://github.com/OpenIdentityPlatform/commons) libraries

**Comment by vharseko** [comment]
[ERROR] Failed to execute goal on project openam-ui-ria: Could not resolve dependencies for project org.openidentityplatform.openam:openam-ui-ria:pom:14.5.4-SNAPSHOT: The following artifacts could not be resolved: org.openidentityplatform.commons.ui.libs:moment:js:min:2.8.1, org.openidentityplatform.commons.ui.libs:handlebars:js:4.4.2: Failure to find org.openidentityplatform.commons.ui.libs:moment:js:min:2.8.1 in https://maven-central.storage-download.googleapis.com/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of google-maven-central has elapsed or updates are forced -> [Help 1]

**Comment by maximthomas** [comment]
Artifacts` org.openidentityplatform.commons.ui.libs:*` should be installed in a central maven repo while building [OpenIdentityPlatform/commons](https://github.com/OpenIdentityPlatform/commons) project, but they are not, so it causes the build error

**Comment by maximthomas** [comment]
there is another issue - current version of commons 2.0.8-SNAPHSOT, i think we should release 2.0.8 of commons and update pom of current project

**Pull request merged**
