### PR TITLE
NTLMv2 authentication module

### PR DESCRIPTION
**Pull request by maximthomas**

### CODE REVIEW

**Comment by lscorcia** [comment]
Hi, I'm trying to test this but I can't activate the module. I built the latest sources, then ran it using cargo. Set up login.domain.com in the hosts file and completed the first time setup (passwords, embedded OpenDJ etc). I created a new realm and went into Authentication > Modules > New module. Set name: "NTLM", Type: "NTLM", but I get the error: "Parent service does not exist"

immagine

Is there any prerequisite to activate it?

**Comment by maximthomas** [comment]
@lscorcia Hi, I can't rerpoduce this issue. As a workaround I suggest you to add this module in classic UI. To enable classic UI, set system property `-DXUI.enable=false`

**Comment by maximthomas** [comment]
@lscorcia seems I've figured out the cause of the problem. I'll fix it as soon as possible

**Comment by maximthomas** [comment]
@lscorcia take a look at #581 PR

**Comment by lscorcia** [comment]
Yes, I can confirm that now the config screen loads fine! Thanks!

**Pull request merged**
